# Pytorch Basics and Fundamentals

In [1]:
# importing pytorch
import torch
# checking version
print(torch.__version__)
# checking if cuda is available
print(torch.cuda.is_available())

1.8.1+cpu
False


### Tensor Basics

In [2]:
# let's create uninitialized tensors
x = torch.empty(1) # creates scalar tensor with uninitialized value
y = torch.empty(2) # creates a 1-d tensor with 2 items
z = torch.empty(2,2) # creates a matrix of order 2 X 2
x, y, z

(tensor([2.1679e-36]),
 tensor([2.1681e-36, 4.5628e-41]),
 tensor([[2.1680e-36, 4.5628e-41],
         [2.1680e-36, 4.5628e-41]]))

In [3]:
# Let's create random tensors
x = torch.rand(1) # creates  a scalar tensor with random value
y = torch.rand(3) # creates a 1-D tensor with random value
z = torch.rand(2, 3, 4) # creates a 3-D tensor with shape 2 X 3 X 4
x, y, z

(tensor([0.0936]),
 tensor([0.7886, 0.9719, 0.0831]),
 tensor([[[0.8098, 0.5733, 0.5463, 0.8043],
          [0.8922, 0.4024, 0.3917, 0.0103],
          [0.6677, 0.7331, 0.0527, 0.3096]],
 
         [[0.3559, 0.2101, 0.0282, 0.7960],
          [0.3713, 0.5057, 0.8628, 0.4406],
          [0.0462, 0.8363, 0.9178, 0.9018]]]))

In [4]:
# let's create tensor with all zeros
x = torch.zeros(2,2) # creates a tensor with 2 X 2 zero matrix
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [5]:
# let's create tensor with all ones
x = torch.ones(1,2,3) # creates a tensor with 1 X 2 X 3 shape
print(x)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])


In [6]:
# we can check data type of values inside tensor
print(x.dtype)

torch.float32


In [7]:
# we can provide data type while creating tensor
x = torch.rand(2,3, dtype=torch.float32)
print(x)

tensor([[0.9921, 0.2044, 0.1462],
        [0.8446, 0.3872, 0.0745]])


In [8]:
# we can create tensor from python list
x = torch.tensor([1.0,2.0,3.0])
print(x)

tensor([1., 2., 3.])


## Tensor Operations

In [9]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
x + y, x - y, x * y, x / y, x ** y # element-wise operations in tensors using pytorch 

tensor([[0.1202, 0.2123],
        [0.7354, 0.4825]])
tensor([[0.6444, 0.0565],
        [0.2706, 0.7648]])


(tensor([[0.7646, 0.2687],
         [1.0059, 1.2474]]),
 tensor([[-0.5242,  0.1558],
         [ 0.4648, -0.2823]]),
 tensor([[0.0775, 0.0120],
         [0.1990, 0.3691]]),
 tensor([[0.1865, 3.7602],
         [2.7180, 0.6309]]),
 tensor([[0.2553, 0.9162],
         [0.9202, 0.5727]]))

In [10]:
# we can also do inplace operations as below
y.add_(x)  # this is inplace operations

tensor([[0.7646, 0.2687],
        [1.0059, 1.2474]])

In [11]:
z = x - y
z = torch.sub(x,y) # subtraction
z = torch.mul(x,y) # multiplication
z = torch.div(x,y) # division

### Slicing and Dicing

In [12]:
# pytorch tensors can be sliced and diced like we do in python

In [13]:
x = torch.rand((5,3), dtype=torch.float32)
print(x)
print(x[1, :]) # this will give me everything from second row till end (all columns selected)
print(x[1][1]) # this will give me one value at 2nd row and 2nd column

tensor([[0.8093, 0.3960, 0.2067],
        [0.6688, 0.3893, 0.7853],
        [0.6731, 0.2612, 0.6845],
        [0.7880, 0.9713, 0.3054],
        [0.7486, 0.2530, 0.5806]])
tensor([0.6688, 0.3893, 0.7853])
tensor(0.3893)


### Reshaping

In [14]:
# let's create a random tensor of 1 dimension with 20 elements
x = torch.rand((20,), dtype=torch.float32)
print(x)
print(x.shape) # check size of the tensor

tensor([0.2568, 0.5926, 0.7623, 0.5663, 0.6511, 0.5495, 0.5028, 0.4700, 0.5850,
        0.6629, 0.8817, 0.6449, 0.0474, 0.1722, 0.9978, 0.9290, 0.2973, 0.7462,
        0.4549, 0.0275])
torch.Size([20])


In [15]:
# let's reshape this to 5 X 4 shape
print(x.reshape((5,4))) # of new shape 5 X 4
print(x.reshape((4,5))) # of new shape 4 X 5
print(x.reshape((-1,4))) # row is calculated automaticallye
print(x.reshape((4,-1))) # column is calculated automatically

tensor([[0.2568, 0.5926, 0.7623, 0.5663],
        [0.6511, 0.5495, 0.5028, 0.4700],
        [0.5850, 0.6629, 0.8817, 0.6449],
        [0.0474, 0.1722, 0.9978, 0.9290],
        [0.2973, 0.7462, 0.4549, 0.0275]])
tensor([[0.2568, 0.5926, 0.7623, 0.5663, 0.6511],
        [0.5495, 0.5028, 0.4700, 0.5850, 0.6629],
        [0.8817, 0.6449, 0.0474, 0.1722, 0.9978],
        [0.9290, 0.2973, 0.7462, 0.4549, 0.0275]])
tensor([[0.2568, 0.5926, 0.7623, 0.5663],
        [0.6511, 0.5495, 0.5028, 0.4700],
        [0.5850, 0.6629, 0.8817, 0.6449],
        [0.0474, 0.1722, 0.9978, 0.9290],
        [0.2973, 0.7462, 0.4549, 0.0275]])
tensor([[0.2568, 0.5926, 0.7623, 0.5663, 0.6511],
        [0.5495, 0.5028, 0.4700, 0.5850, 0.6629],
        [0.8817, 0.6449, 0.0474, 0.1722, 0.9978],
        [0.9290, 0.2973, 0.7462, 0.4549, 0.0275]])


In [16]:
print(torch.rand(4,4)) # returns a tensor of 4X 4 with random numbers between 0 to 1 from uniform distribution
print(torch.randn(4,4)) # returns a tensor fo 4 X 4 with random numbers from normal distribution with mean 0 and variance 1

tensor([[0.5828, 0.5307, 0.5640, 0.9250],
        [0.1986, 0.1017, 0.0312, 0.0629],
        [0.0571, 0.1832, 0.8954, 0.6430],
        [0.5508, 0.3677, 0.2865, 0.1033]])
tensor([[-1.2179, -0.9530, -0.0465,  0.1031],
        [ 1.2059,  0.6695,  0.2507, -0.0790],
        [-1.5268,  1.6806, -0.8435,  1.1017],
        [-0.9922,  0.7886,  1.0129, -0.5631]])


In [21]:
# we can also use view function in pytorch
print(x.view(-1,5))

tensor([[0.2568, 0.5926, 0.7623, 0.5663, 0.6511],
        [0.5495, 0.5028, 0.4700, 0.5850, 0.6629],
        [0.8817, 0.6449, 0.0474, 0.1722, 0.9978],
        [0.9290, 0.2973, 0.7462, 0.4549, 0.0275]])


### Tensorflow to numpy and viceversa

In [22]:
import torch
import numpy as np

In [25]:
# initialize torch array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
# convert to numpy
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [31]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a) # converting to tensor from numpy
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [32]:
# setting GPU if available
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)