# Dataset and dataloader

In [5]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('./datasets/wine.csv', header=0)
df.head()

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [11]:
data = df.to_numpy() # converting dataframe to numpy

In [12]:
# below process is very time consuming
# training loop
# for epoch in range(1000):
    # x,y = data
    # foward + backward + weights updates  

In [13]:
# --> use Dataset and DataLoader to load wine.csv

In [14]:
print('''
epoch = 1 forward and backward pass of all training samples
batch_size = number of training samples in one forward and backward pass
number of iterations = number of passes, each pass using [batch_size] number of samples

e.g 100 samples, batch_size=20 --> 100/20 = 5 iterations for 1 epoch
''')


epoch = 1 forward and backward pass of all training samples
batch_size = number of training samples in one forward and backward pass
number of iterations = number of passes, each pass using [batch_size] number of samples

e.g 100 samples, batch_size=20 --> 100/20 = 5 iterations for 1 epoch



In [15]:
# import packages 
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [20]:
class WineDataset(Dataset):
    def __init__(self):
        # data loading
        data = np.loadtxt('./datasets/wine.csv', delimiter = ',', dtype=np.float32, skiprows=1)
        self.x = torch.from_numpy(data[:, 1:])
        self.y = torch.from_numpy(data[:, [0]]) # n_samples, 1
        self.n_samples = data.shape[0]
        
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return self.n_samples

In [21]:
dataset = WineDataset()
first_data = dataset[0]
features, labels = first_data
print(features, labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [22]:
dataset = WineDataset()
dataloader = DataLoader(dataset = dataset, batch_size = 4, shuffle = True, num_workers=2)

In [23]:
data_iter = iter(dataloader) # converting dataloader to iterable
data = data_iter.next()
features, labels = data
print(features, labels)

tensor([[1.3560e+01, 1.7100e+00, 2.3100e+00, 1.6200e+01, 1.1700e+02, 3.1500e+00,
         3.2900e+00, 3.4000e-01, 2.3400e+00, 6.1300e+00, 9.5000e-01, 3.3800e+00,
         7.9500e+02],
        [1.3390e+01, 1.7700e+00, 2.6200e+00, 1.6100e+01, 9.3000e+01, 2.8500e+00,
         2.9400e+00, 3.4000e-01, 1.4500e+00, 4.8000e+00, 9.2000e-01, 3.2200e+00,
         1.1950e+03],
        [1.3840e+01, 4.1200e+00, 2.3800e+00, 1.9500e+01, 8.9000e+01, 1.8000e+00,
         8.3000e-01, 4.8000e-01, 1.5600e+00, 9.0100e+00, 5.7000e-01, 1.6400e+00,
         4.8000e+02],
        [1.3820e+01, 1.7500e+00, 2.4200e+00, 1.4000e+01, 1.1100e+02, 3.8800e+00,
         3.7400e+00, 3.2000e-01, 1.8700e+00, 7.0500e+00, 1.0100e+00, 3.2600e+00,
         1.1900e+03]]) tensor([[1.],
        [1.],
        [3.],
        [1.]])


In [25]:
# let's create dummy training loop
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples / 4)
print(total_samples, n_iterations)

178 45


In [26]:
for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        # forward  backward, update
        if (i + 1) % 5 == 0:
            print(f'epoch : {epoch + 1}/{num_epochs}, step {i+1}/{n_iterations}, inputs {inputs.shape}')

epoch : 1/2, step 5/45, inputs torch.Size([4, 13])
epoch : 1/2, step 10/45, inputs torch.Size([4, 13])
epoch : 1/2, step 15/45, inputs torch.Size([4, 13])
epoch : 1/2, step 20/45, inputs torch.Size([4, 13])
epoch : 1/2, step 25/45, inputs torch.Size([4, 13])
epoch : 1/2, step 30/45, inputs torch.Size([4, 13])
epoch : 1/2, step 35/45, inputs torch.Size([4, 13])
epoch : 1/2, step 40/45, inputs torch.Size([4, 13])
epoch : 1/2, step 45/45, inputs torch.Size([2, 13])
epoch : 2/2, step 5/45, inputs torch.Size([4, 13])
epoch : 2/2, step 10/45, inputs torch.Size([4, 13])
epoch : 2/2, step 15/45, inputs torch.Size([4, 13])
epoch : 2/2, step 20/45, inputs torch.Size([4, 13])
epoch : 2/2, step 25/45, inputs torch.Size([4, 13])
epoch : 2/2, step 30/45, inputs torch.Size([4, 13])
epoch : 2/2, step 35/45, inputs torch.Size([4, 13])
epoch : 2/2, step 40/45, inputs torch.Size([4, 13])
epoch : 2/2, step 45/45, inputs torch.Size([2, 13])


## Transforms for datasets 

In [27]:
# import packages 
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [33]:
class WineDataset(Dataset):
    def __init__(self, transform=None):
        # data loading
        data = np.loadtxt('./datasets/wine.csv', delimiter = ',', dtype=np.float32, skiprows=1)
        self.x = data[:, 1:]
        self.y = data[:, [0]] # n_samples, 1
        self.n_samples = data.shape[0]
        self.transform = transform
        
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample 
    
    def __len__(self):
        return self.n_samples

In [34]:
# custom Transform
class ToTensor:
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

In [35]:
dataset = WineDataset(transform = ToTensor())

In [36]:
# let's get the first data
first_data = dataset[0]
features, labels = first_data
print(type(features), type(labels))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [37]:
# let's create another custom transform
class MulTransform:
    def __init__(self, factor):
        self.factor = factor
        
    def __call__(self, sample):
        inputs, target = sample
        inputs *= self.factor
        return inputs, target

In [39]:
# create a composed transform
composed = torchvision.transforms.Compose ([
    ToTensor(),
    MulTransform(2)
])

dataset = WineDataset(transform = composed)
# let's get the first data
first_data = dataset[0]
features, labels = first_data
print(features)
print(type(features), type(labels))

tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03])
<class 'torch.Tensor'> <class 'torch.Tensor'>
